// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/minitauros/go-concurrency-training/courses/testing/6_tdd"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserRepo creates a new instance of MockUserRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepo {
	mock := &MockUserRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepo is an autogenerated mock type for the UserRepo type
type MockUserRepo struct {
	mock.Mock
}

type MockUserRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepo) EXPECT() *MockUserRepo_Expecter {
	return &MockUserRepo_Expecter{mock: &_m.Mock}
}

// Ban provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) Ban(ctx context.Context, userID int64) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Ban")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepo_Ban_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ban'
type MockUserRepo_Ban_Call struct {
	*mock.Call
}

// Ban is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockUserRepo_Expecter) Ban(ctx interface{}, userID interface{}) *MockUserRepo_Ban_Call {
	return &MockUserRepo_Ban_Call{Call: _e.mock.On("Ban", ctx, userID)}
}

func (_c *MockUserRepo_Ban_Call) Run(run func(ctx context.Context, userID int64)) *MockUserRepo_Ban_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_Ban_Call) Return(err error) *MockUserRepo_Ban_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepo_Ban_Call) RunAndReturn(run func(ctx context.Context, userID int64) error) *MockUserRepo_Ban_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) GetUser(ctx context.Context, userID int64) (tdd.User, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 tdd.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (tdd.User, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) tdd.User); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(tdd.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockUserRepo_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockUserRepo_Expecter) GetUser(ctx interface{}, userID interface{}) *MockUserRepo_GetUser_Call {
	return &MockUserRepo_GetUser_Call{Call: _e.mock.On("GetUser", ctx, userID)}
}

func (_c *MockUserRepo_GetUser_Call) Run(run func(ctx context.Context, userID int64)) *MockUserRepo_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_GetUser_Call) Return(user tdd.User, err error) *MockUserRepo_GetUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepo_GetUser_Call) RunAndReturn(run func(ctx context.Context, userID int64) (tdd.User, error)) *MockUserRepo_GetUser_Call {
	_c.Call.Return(run)
	return _c
}
