dir: '{{.InterfaceDir}}/mocks'
filename: '{{.InterfaceName | snakecase}}_mock.go'
pkgname: 'mocks'
packages:
  github.com/minitauros/go-concurrency-training/course/7_kafka_consumer/solution/real:
    interfaces:
      WrappedConsumer: